# Permalinks
permalink: pretty

# Gems
gems: [jekyll-gist, jekyll-paginate]

# Setup
title: Vincent Garrigues
url: https://garriguv.github.io/
paginate: 10
paginate_path: "/blog/:num/"
baseurl: ''
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Pages list
pages_list:
  Blog: '/blog'
  Talks: '/talks'
  Feed: '/atom.xml'

# About/contact
author:
  name: Vincent Garrigues
  url: https://garriguv.io
  email: vincent@garriguv.io
