# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: Vincent Garrigues
url: https://garriguv.github.io/
paginate: 1
baseurl: ''
markdown: kramdown
highlighter: pygment

kramdown:
  input: GFM

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Pages list
pages_list:
  About: '/about'
  Talks: '/talks'
  Feed: '/atom.xml'

# About/contact
author:
  name: Vincent Garrigues
  url: https://garriguv.io
  email: vincent.garrigues@gmail.com
